export {default as ARGUMENTS} from './ARGUMENTS';
export {default as AsyncFunction} from './AsyncFunction';
export {default as COMPARE} from './COMPARE';
export {default as GeneratorFunction} from './GeneratorFunction';
export {default as IDENTITY} from './IDENTITY';
export {default as NOOP} from './NOOP';
export {default as is} from './is';
export {default as isAsync} from './isAsync';
export {default as isGenerator} from './isGenerator';
